"""
communication_parser.py

SecureSense AI communication metadata adapter.

Converts the generic entity dictionary produced by the
EntityExtractor into normalized communication metadata used
by the Authenticity Verification Engine (AVE).

This module intentionally remains independent of the entity
extraction implementation.

Supported metadata includes:
- Sender email
- Sender phone number
- Website / URL / domain
- Claimed sender / organisation

The parser supports both the canonical SecureSense entity
keys and compatible aliases.
"""

from dataclasses import dataclass
from typing import Any, Optional


# ==========================================================
# Communication Metadata
# ==========================================================

@dataclass
class CommunicationMetadata:
    """
    Normalized communication metadata consumed by the
    Authenticity Verification Engine.
    """

    sender_email: Optional[str] = None

    sender_phone: Optional[str] = None

    website: Optional[str] = None

    claimed_sender: Optional[str] = None


# ==========================================================
# Communication Parser
# ==========================================================

class CommunicationParser:
    """
    Convert the generic entity dictionary generated by the
    SecureSense analysis pipeline into normalized metadata.

    The canonical EntityExtractor currently produces keys
    including:

        urls
        emails
        phone_numbers
        upi_ids
        bank_accounts
        ifsc_codes
        pan_numbers
        aadhaar_numbers
        money_amounts
        percentages
        sebi_numbers
        dates

    Only metadata relevant to sender authenticity verification
    is extracted here.
    """

    # ------------------------------------------------------
    # Canonical + compatible entity keys
    # ------------------------------------------------------

    EMAIL_KEYS = (
        "emails",
        "email",
        "sender_email",
        "sender_emails",
    )

    PHONE_KEYS = (
        "phone_numbers",
        "phone_number",
        "phones",
        "phone",
        "mobile",
        "mobile_number",
        "contact",
        "contact_number",
    )

    WEBSITE_KEYS = (
        "urls",
        "url",
        "website",
        "websites",
        "domain",
        "domains",
        "link",
        "links",
    )

    CLAIMED_SENDER_KEYS = (
        "claimed_sender",
        "organisation",
        "organisations",
        "organization",
        "organizations",
        "company",
        "companies",
        "bank",
        "banks",
        "sender",
        "sender_name",
    )

    # ======================================================
    # Main Parser
    # ======================================================

    def parse(
        self,
        entities: dict[str, Any],
    ) -> CommunicationMetadata:
        """
        Convert an entity dictionary into normalized
        communication metadata.

        Missing values are represented as None.
        """

        if not entities:

            return CommunicationMetadata()

        if not isinstance(
            entities,
            dict,
        ):

            return CommunicationMetadata()

        return CommunicationMetadata(

            sender_email=self._first(
                entities,
                self.EMAIL_KEYS,
            ),

            sender_phone=self._first(
                entities,
                self.PHONE_KEYS,
            ),

            website=self._first(
                entities,
                self.WEBSITE_KEYS,
            ),

            claimed_sender=self._first(
                entities,
                self.CLAIMED_SENDER_KEYS,
            ),
        )

    # ======================================================
    # First Valid Value
    # ======================================================

    @staticmethod
    def _first(
        data: dict[str, Any],
        keys: tuple[str, ...],
    ) -> Optional[str]:
        """
        Return the first usable value found for the supplied
        keys.

        Supported input forms:
        - string
        - list
        - tuple
        - set

        Empty values are ignored.
        """

        for key in keys:

            value = data.get(
                key
            )

            if value is None:
                continue

            # ------------------------------------------------
            # Direct string value
            # ------------------------------------------------

            if isinstance(
                value,
                str,
            ):

                cleaned = (
                    value.strip()
                )

                if cleaned:

                    return cleaned

            # ------------------------------------------------
            # Collection of values
            # ------------------------------------------------

            elif isinstance(
                value,
                (list, tuple, set),
            ):

                for item in value:

                    if item is None:
                        continue

                    cleaned = str(
                        item
                    ).strip()

                    if cleaned:

                        return cleaned

            # ------------------------------------------------
            # Defensive fallback for other scalar values
            # ------------------------------------------------

            elif not isinstance(
                value,
                (dict, bytes, bytearray),
            ):

                cleaned = str(
                    value
                ).strip()

                if cleaned:

                    return cleaned

        return None


# ==========================================================
# Singleton
# ==========================================================

communication_parser = CommunicationParser()