"""
evidence_models.py

Core evidence models for the SecureSense AI
Explainable Evidence Ledger (EEL).

The EEL provides a standard representation for evidence
generated by different SecureSense intelligence modules.

Supported explainability:
    - URL Intelligence: TreeSHAP feature evidence
    - Visual Phishing Intelligence: Grad-CAM evidence
    - NLP Security Analysis: Integrated Gradients token evidence
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field


# ============================================================
# Feature-Level Evidence
# ============================================================

class FeatureEvidence(BaseModel):
    """
    Feature-level explainability evidence produced by an
    AI model.

    Example:
        URL TreeSHAP contribution.
    """

    feature: str

    value: Any

    contribution: float

    direction: str

    strength: float


# ============================================================
# NLP Token-Level Evidence
# ============================================================

class TokenEvidence(BaseModel):
    """
    Token-level attribution generated by an NLP model.

    Used by the DistilBERT Integrated Gradients
    explainability pipeline.
    """

    token: str

    token_index: int

    attribution: float

    strength: float

    normalized_strength: float

    direction: str


class NLPExplanationEvidence(BaseModel):
    """
    Compact NLP explainability evidence.

    Stores the target class and the most influential tokens
    rather than the complete attribution tensor.
    """

    method: str

    target_class: int

    target_label: str

    target_probability: float

    steps: int

    token_count: int

    top_tokens: List[TokenEvidence] = Field(
        default_factory=list
    )


# ============================================================
# Visual Attention Point
# ============================================================

class VisualAttentionPoint(BaseModel):
    """
    Location of maximum visual-model attention.

    Pixel coordinates preserve the location in the original
    screenshot while normalised coordinates make the evidence
    independent of screenshot resolution.
    """

    x: int

    y: int

    x_normalized: float

    y_normalized: float


# ============================================================
# Visual Explainability Evidence
# ============================================================

class VisualEvidence(BaseModel):
    """
    Compact explainability evidence generated by a visual
    intelligence model.

    The full Grad-CAM heatmap is intentionally NOT stored in
    the EEL because it may contain millions of values.
    """

    method: str

    target_class: int

    target_label: str

    target_probability: float

    target_layer: str

    image_width: int

    image_height: int

    mean_attention: float

    max_attention: float

    high_attention_ratio: float

    max_attention_point: VisualAttentionPoint


# ============================================================
# Model Information
# ============================================================

class EvidenceModelInfo(BaseModel):
    """
    Identifies the model/module responsible for evidence.
    """

    module: str

    model_type: str

    model_file: Optional[str] = None

    feature_count: Optional[int] = None

    model_version: Optional[str] = None

    input_size: Optional[str] = None

    decision_threshold: Optional[float] = None


# ============================================================
# Evidence Record
# ============================================================

class EvidenceRecord(BaseModel):
    """
    Standard auditable evidence record generated by any
    SecureSense AI intelligence module.

    Explainability fields:
        explanation
            Feature-level evidence such as URL TreeSHAP.

        visual_explanation
            Visual evidence such as Grad-CAM.

        nlp_explanation
            Token-level NLP evidence such as
            Integrated Gradients.
    """

    evidence_id: str = Field(
        default_factory=lambda: (
            f"EEL-{uuid4().hex[:12].upper()}"
        )
    )

    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(
            timezone.utc
        )
    )

    # --------------------------------------------------------
    # Source
    # --------------------------------------------------------

    module: str

    evidence_type: str

    input_reference: Optional[str] = None

    # --------------------------------------------------------
    # AI decision
    # --------------------------------------------------------

    prediction: str

    class_id: Optional[int] = None

    confidence: float

    risk_score: float

    # --------------------------------------------------------
    # Feature-based explainability
    #
    # URL Intelligence / TreeSHAP
    # --------------------------------------------------------

    explanation: List[FeatureEvidence] = Field(
        default_factory=list
    )

    # --------------------------------------------------------
    # Visual explainability
    #
    # Visual Phishing Intelligence / Grad-CAM
    # --------------------------------------------------------

    visual_explanation: Optional[
        VisualEvidence
    ] = None

    # --------------------------------------------------------
    # NLP explainability
    #
    # NLP Security Analysis / Integrated Gradients
    # --------------------------------------------------------

    nlp_explanation: Optional[
        NLPExplanationEvidence
    ] = None

    # --------------------------------------------------------
    # Model metadata
    # --------------------------------------------------------

    model_info: EvidenceModelInfo

    # --------------------------------------------------------
    # Supporting evidence / metadata
    # --------------------------------------------------------

    supporting_data: Dict[str, Any] = Field(
        default_factory=dict
    )


# ============================================================
# Ledger Response
# ============================================================

class EvidenceLedgerEntry(BaseModel):
    """
    Wrapper returned when evidence is committed to the
    Explainable Evidence Ledger.
    """

    ledger_id: str

    recorded_at: datetime

    evidence: EvidenceRecord