"""
ledger.py

Explainable Evidence Ledger (EEL) for SecureSense AI.

Provides a central mechanism for recording auditable
evidence generated by NLP, URL, vision, voice and other
trust-intelligence modules.
"""

from datetime import datetime, timezone
from threading import Lock
from typing import List
from uuid import uuid4

from app.eel.evidence_models import (
    EvidenceLedgerEntry,
    EvidenceRecord,
)


class ExplainableEvidenceLedger:
    """
    Central SecureSense runtime evidence ledger.

    Responsibilities:
        - Create auditable ledger entries
        - Maintain process-local evidence during analysis
        - Provide immediate ledger lookup during orchestration

    Durable persistence:
        Completed ledger entries are persisted separately through
        the EEL persistence service and associated with their
        communication ID.

    Historical retrieval must use the persistent EEL database
    rather than this process-local collection.
    """

    def __init__(self) -> None:

        self._entries: List[
            EvidenceLedgerEntry
        ] = []

        self._lock = Lock()

    # ========================================================
    # Record Evidence
    # ========================================================

    def record(
        self,
        evidence: EvidenceRecord,
    ) -> EvidenceLedgerEntry:
        """
        Commit an evidence record to the ledger.
        """

        entry = EvidenceLedgerEntry(
            ledger_id=(
                f"LEDGER-"
                f"{uuid4().hex[:12].upper()}"
            ),

            recorded_at=datetime.now(
                timezone.utc
            ),

            evidence=evidence,
        )

        with self._lock:
            self._entries.append(entry)

        return entry

    # ========================================================
    # Retrieve Evidence
    # ========================================================

    def get(
        self,
        ledger_id: str,
    ) -> EvidenceLedgerEntry | None:

        with self._lock:

            for entry in self._entries:

                if entry.ledger_id == ledger_id:
                    return entry

        return None

    # ========================================================
    # Retrieve All Evidence
    # ========================================================

    def all(
        self,
    ) -> List[EvidenceLedgerEntry]:

        with self._lock:
            return list(self._entries)

    # ========================================================
    # Ledger Size
    # ========================================================

    def count(
        self,
    ) -> int:

        with self._lock:
            return len(self._entries)


# ============================================================
# Singleton
# ============================================================

evidence_ledger = ExplainableEvidenceLedger()