"""
calculators.py

Utility functions used while generating the
Financial Communication Passport (FCP).
"""

from collections import Counter

from app.models.analysis_models import AnalysisResult
from app.fcp.models import EvidenceSummary


# ============================================================
# Trust Score
# ============================================================

def calculate_trust_score(
    risk_score: float,
    verification_bonus: float = 0.0,
    reputation_bonus: float = 0.0,
    evidence_bonus: float = 0.0,
) -> float:
    """
    Calculate the overall trust score.

    Trust is currently derived primarily from the final
    communication-level risk score:

        trust_score = 100 - risk_score

    Optional bonuses are retained for future trust-layer
    extensions such as:

    - Authenticity Verification Engine (AVE)
    - Historical reputation
    - Securities Trust Graph intelligence
    - Evidence quality

    The result is:
    - bounded to 0-100
    - rounded to avoid floating-point artefacts
    """

    score = (
        100.0
        - float(risk_score)
        + float(verification_bonus)
        + float(reputation_bonus)
        + float(evidence_bonus)
    )

    # Keep trust inside the valid 0-100 range.
    score = max(
        0.0,
        min(
            100.0,
            score,
        ),
    )

    # Prevent values such as:
    #
    # 0.0006000000000057071
    #
    # while retaining useful precision for ML-derived scores.
    return round(
        score,
        4,
    )


# ============================================================
# Evidence Summary
# ============================================================

def build_evidence_summary(
    analysis: AnalysisResult,
) -> EvidenceSummary:
    """
    Build a compact summary of deterministic findings.

    Explainability evidence generated by ML modules is attached
    separately through the Explainable Evidence Ledger.
    """

    counter = Counter()

    for finding in analysis.findings:

        counter[
            finding.severity.lower()
        ] += 1

    return EvidenceSummary(

        total_findings=len(
            analysis.findings
        ),

        high_severity=counter.get(
            "high",
            0,
        ),

        medium_severity=counter.get(
            "medium",
            0,
        ),

        low_severity=counter.get(
            "low",
            0,
        ),
    )


# ============================================================
# Recommended Action
# ============================================================

def get_recommended_action(
    risk_level: str,
) -> str:
    """
    Return the user-facing action associated with the final
    communication-level risk classification.
    """

    mapping = {

        "Low":
            (
                "Communication appears relatively safe. "
                "Continue with normal caution."
            ),

        "Medium":
            (
                "Verify the sender independently before "
                "taking any financial action."
            ),

        "High":
            (
                "Do not transfer money, scan QR codes or "
                "share credentials until authenticity has "
                "been independently verified."
            ),
    }

    return mapping.get(
        risk_level,
        "Exercise caution.",
    )