"""
models.py

Financial Communication Passport (FCP) models.

The FCP is the standardized trust object generated by
SecureSense AI from intelligence, verification, historical
graph context and explainable evidence.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class VerificationStatus(BaseModel):
    """
    Results from the Authenticity Verification Engine (AVE).
    """

    official_domain: bool = False
    official_provider: Optional[str] = None
    registered_domain: Optional[str] = None
    official_email: bool = False
    official_phone: bool = False
    official_qr: bool = False
    digital_signature: bool = False
    metadata_consistent: bool = True

    verification_confidence: float = 0.0

    # Important distinction:
    # False indicators do NOT automatically mean verification failed.
    # The verification engine may simply not have run yet.
    status: str = "Not Performed"


class EvidenceSummary(BaseModel):
    """
    Summary of evidence supporting the passport decision.
    """

    total_findings: int = 0

    high_severity: int = 0
    medium_severity: int = 0
    low_severity: int = 0

    evidence_ids: List[str] = Field(
        default_factory=list
    )

    ledger_ids: List[str] = Field(
        default_factory=list
    )

    modules: List[str] = Field(
        default_factory=list
    )


class ExplainableEvidenceItem(BaseModel):
    """
    Human-readable evidence surfaced by the FCP.
    """

    source_module: str

    feature: str

    value: Any

    contribution: float

    direction: str

    strength: float


# ============================================================
# Securities Trust Graph Relationship Context
# ============================================================

class FCPRelationshipSignal(BaseModel):
    """
    Compact relationship-derived signal surfaced by the FCP.

    A relationship signal describes contextual graph evidence
    associated with an STG subject entity.

    Relationship-derived evidence is intentionally kept
    separate from direct entity reputation and sender
    authentication.

    A relationship does NOT by itself establish that the
    subject entity is malicious, trusted, or authenticated.
    """

    relationship_type: str = "UNKNOWN"

    neighbour_node_id: str = ""

    neighbour_type: str = "Unknown"

    neighbour_value: str = ""

    neighbour_classification: str = "Unknown"

    neighbour_risk_score: Optional[float] = None

    risk_contribution: float = 0.0

    trust_contribution: float = 0.0

    confidence: float = 0.0

    evidence_ids: List[str] = Field(
        default_factory=list
    )

    ledger_ids: List[str] = Field(
        default_factory=list
    )

    reason: str = ""


class FCPRelationshipContextItem(BaseModel):
    """
    Relationship-derived contextual intelligence for one
    STG subject entity.

    This model intentionally preserves per-entity context.

    Scores belonging to unrelated entities must not be
    averaged together into an artificial global graph score.
    """

    subject_node_id: str

    available: bool = False

    contextual_risk_score: Optional[float] = None

    contextual_trust_score: Optional[float] = None

    confidence: float = 0.0

    classification: str = "Unknown"

    relationships_analysed: int = 0

    contributing_relationships: int = 0

    high_risk_neighbours: int = 0

    suspicious_neighbours: int = 0

    trusted_neighbours: int = 0

    signals: List[
        FCPRelationshipSignal
    ] = Field(
        default_factory=list
    )

    evidence_ids: List[str] = Field(
        default_factory=list
    )

    ledger_ids: List[str] = Field(
        default_factory=list
    )

    reasons: List[str] = Field(
        default_factory=list
    )

    summary: str = (
        "No relationship-derived contextual intelligence "
        "is currently available."
    )


class FCPRelationshipContext(BaseModel):
    """
    Compact relationship-derived STG context stored in the
    Financial Communication Passport.

    Relationship intelligence remains a separate contextual
    dimension from:

    - communication-level security risk
    - direct historical entity reputation
    - sender authenticity / AVE verification

    Per-entity relationship contexts are retained separately.
    No artificial global relationship risk/trust average is
    produced.

    Relationship-derived evidence may strengthen contextual
    caution, but it must never authenticate a sender or
    silently override the trained communication-level
    security decision.
    """

    available: bool = False

    contexts_analysed: int = 0

    contexts_available: int = 0

    total_signals: int = 0

    contexts: List[
        FCPRelationshipContextItem
    ] = Field(
        default_factory=list
    )

    evidence_ids: List[str] = Field(
        default_factory=list
    )

    ledger_ids: List[str] = Field(
        default_factory=list
    )

    summary: str = (
        "No relationship-derived STG context is currently "
        "available."
    )

    contextual_role: str = (
        "Relationship-derived graph context only. "
        "Does not create direct entity-security evidence, "
        "authenticate the sender, or override "
        "communication-level security analysis."
    )


# ============================================================
# Securities Trust Graph Context
# ============================================================

class SecuritiesTrustGraphContext(BaseModel):
    """
    Historical entity-reputation context supplied by the
    Securities Trust Graph (STG).

    This information is intentionally kept separate from:

    - communication-level risk
    - sender authenticity
    - AVE verification

    A trusted entity does NOT authenticate the sender and does
    NOT make suspicious communication content safe.

    Likewise, historical high-risk entity evidence may provide
    additional security context without replacing the trained
    communication-level model decision.

    Relationship-derived context is exposed independently from
    direct entity reputation so that graph associations cannot
    silently become direct security evidence.
    """

    available: bool = False

    reputation_available: bool = False

    classification: str = "Unknown"

    graph_risk_score: Optional[float] = None

    graph_trust_score: Optional[float] = None

    confidence: float = 0.0

    entities_analysed: int = 0

    # --------------------------------------------------------
    # Relationship-Derived Context
    # --------------------------------------------------------
    #
    # Relationship intelligence is intentionally nested under
    # STG but kept separate from direct historical reputation.
    #
    # It must not:
    #
    # - authenticate the sender
    # - create direct reputation evidence
    # - overwrite graph_risk_score
    # - overwrite graph_trust_score
    # - modify communication-level risk
    # --------------------------------------------------------

    relationship_context: Optional[
        FCPRelationshipContext
    ] = None

    evidence_ids: List[str] = Field(
        default_factory=list
    )

    ledger_ids: List[str] = Field(
        default_factory=list
    )

    summary: str = ""

    contextual_role: str = (
        "Historical entity context only. "
        "Does not authenticate the sender or override "
        "communication-level security analysis."
    )


class FinancialCommunicationPassport(BaseModel):
    """
    Standardized Trust Passport for an analysed
    financial communication.
    """

    passport_id: str

    communication_id: Optional[str] = None

    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(
            timezone.utc
        )
    )

    communication_type: str

    claimed_sender: str = "Unknown"

    verified_sender: bool = False

    verification: VerificationStatus

    threat_categories: List[str] = Field(
        default_factory=list
    )

    ai_manipulation_findings: List[str] = Field(
        default_factory=list
    )

    risk_score: float

    risk_level: str

    trust_score: float

    confidence: float

    # --------------------------------------------------------
    # Historical Entity-Reputation Context
    # --------------------------------------------------------
    #
    # STG is intentionally represented as an independent
    # contextual dimension.
    #
    # It must not be interpreted as sender authentication and
    # must not silently modify the trained communication-level
    # risk score.
    #
    # Relationship-derived graph intelligence, when present,
    # is nested inside the STG context and remains separate
    # from direct entity reputation.
    # --------------------------------------------------------

    securities_trust_graph: Optional[
        SecuritiesTrustGraphContext
    ] = None

    evidence: EvidenceSummary

    explainable_evidence: List[
        ExplainableEvidenceItem
    ] = Field(
        default_factory=list
    )

    recommended_action: str